// priority: 0

// Visit the wiki for more info - https://kubejs.com/

console.info('Hello, World! (Loaded server scripts)')
ServerEvents.recipes(event => {
	register_wings(event)
	event.shaped("minecraft:copper_block", [// arg 1: output
    'AAA', 
    'AAA', // arg 2: the shape (array of strings)
    'AAA'  
  ], {
    A: "minecraft:copper_ingot", 
  }
)
})

function register_wings(event) {
let wing = (output, top, center, wing_top, wing_mid, wing_low) => {
event.shaped(output, [// arg 1: output
    'CAC', 
    'DBD', // arg 2: the shape (array of strings)
    'E E'  
  ], {
    A: top, 
    B: center,  //arg 3: the mapping object
    C: wing_top,
    D: wing_mid,
    E: wing_low 
  }
)
}
wing("winged:wing_angel", "winged:core_of_flight", "minecraft:gold_ingot", "winged:angel_feather", "winged:angel_feather", "winged:angel_feather")
wing("winged:wing_angel_creative_flight", "winged:heart_of_the_sky", "minecraft:gold_ingot", "winged:angel_feather", "winged:angel_feather", "winged:angel_feather")
wing("winged:wing_bat", "winged:core_of_flight", null, "winged:bat_wing", "winged:bat_wing", "winged:bat_wing")
wing("winged:wing_bat_alt", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:iron_ingot", "winged:bat_wing", "winged:bat_wing")
wing("winged:wing_bat_alt_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:iron_ingot", "winged:bat_wing", "winged:bat_wing")
wing("winged:wing_bat_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "winged:bat_wing", "winged:bat_wing", "winged:bat_wing")
wing("winged:wing_brazil", "winged:wing_elytra_green", "minecraft:gold_nugget", "minecraft:gold_ingot", "minecraft:lapis_lazuli", "minecraft:gold_nugget")
wing("winged:wing_brazil_creative_flight", "winged:wing_elytra_green_creative_flight", "minecraft:gold_nugget", "minecraft:gold_ingot", "minecraft:lapis_lazuli", "minecraft:gold_nugget")
wing("winged:wing_cobalt_cape", "winged:core_of_flight", "minecraft:diamond", "minecraft:magenta_wool", "winged:irreality_crystal", "minecraft:magenta_wool")
wing("winged:wing_cobalt_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:diamond", "minecraft:magenta_wool", "winged:irreality_crystal", "minecraft:magenta_wool")
wing("winged:wing_creamy_white", "winged:core_of_flight", "minecraft:gold_ingot", "minecraft:milk_bucket", "winged:angel_feather", "winged:angel_feather")
wing("winged:wing_creamy_white_creative_flight", "winged:heart_of_the_sky", "minecraft:gold_ingot", "minecraft:milk_bucket", "winged:angel_feather", "winged:angel_feather")
wing("winged:wing_crowdin_cape", "winged:core_of_flight", "minecraft:gold_ingot", "minecraft:book", "minecraft:paper", "minecraft:paper")
wing("winged:wing_crowdin_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:gold_ingot", "minecraft:book", "minecraft:paper", "minecraft:paper")
wing("winged:wing_dannybstyle_cape", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:blue_wool", "minecraft:yellow_wool", "minecraft:blue_wool")
wing("winged:wing_dannybstyle_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:blue_wool", "minecraft:yellow_wool", "minecraft:blue_wool")
wing("winged:wing_demon", "winged:core_of_flight", "minecraft:gold_ingot", "minecraft:leather", "winged:demonic_flesh", "winged:demonic_flesh")
wing("winged:wing_demon_creative_flight", "winged:heart_of_the_sky", "minecraft:gold_ingot", "minecraft:leather", "winged:demonic_flesh", "winged:demonic_flesh")
wing("winged:wing_dragonfly", "winged:core_of_flight", "minecraft:spider_eye", "minecraft:spider_eye", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_dragonfly_creative_flight", "winged:heart_of_the_sky", "minecraft:spider_eye", "minecraft:spider_eye", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_eagle", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:brown_dye", "minecraft:feather", "minecraft:feather")
wing("winged:wing_eagle_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:brown_dye", "minecraft:feather", "minecraft:feather")
wing("winged:wing_earth", "winged:wing_elytra_light_blue", "minecraft:diamond", "minecraft:emerald", "minecraft:lapis_lazuli", "minecraft:snowball")
wing("winged:wing_earth_creative_flight", "winged:wing_elytra_light_blue_creative_flight", "minecraft:diamond", "minecraft:emerald", "minecraft:lapis_lazuli", "minecraft:snowball")
wing("winged:wing_elytra", "winged:core_of_flight", "minecraft:elytra", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_ingot")
wing("winged:wing_elytra_black", "winged:core_of_flight", "minecraft:elytra", "minecraft:black_wool", "minecraft:black_wool", "minecraft:black_wool")
wing("winged:wing_elytra_black_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:black_wool", "minecraft:black_wool", "minecraft:black_wool")
wing("winged:wing_elytra_blue", "winged:core_of_flight", "minecraft:elytra", "minecraft:blue_wool", "minecraft:blue_wool", "minecraft:blue_wool")
wing("winged:wing_elytra_blue_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:blue_wool", "minecraft:blue_wool", "minecraft:blue_wool")
wing("winged:wing_elytra_brown", "winged:core_of_flight", "minecraft:elytra", "minecraft:brown_wool", "minecraft:brown_wool", "minecraft:brown_wool")
wing("winged:wing_elytra_brown_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:brown_wool", "minecraft:brown_wool", "minecraft:brown_wool")
wing("winged:wing_elytra_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_ingot")
wing("winged:wing_elytra_cyan", "winged:core_of_flight", "minecraft:elytra", "minecraft:cyan_wool", "minecraft:cyan_wool", "minecraft:cyan_wool")
wing("winged:wing_elytra_cyan_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:cyan_wool", "minecraft:cyan_wool", "minecraft:cyan_wool")
wing("winged:wing_elytra_gray", "winged:core_of_flight", "minecraft:elytra", "minecraft:gray_wool", "minecraft:gray_wool", "minecraft:gray_wool")
wing("winged:wing_elytra_gray_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:gray_wool", "minecraft:gray_wool", "minecraft:gray_wool")
wing("winged:wing_elytra_green", "winged:core_of_flight", "minecraft:elytra", "minecraft:green_wool", "minecraft:green_wool", "minecraft:green_wool")
wing("winged:wing_elytra_green_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:green_wool", "minecraft:green_wool", "minecraft:green_wool")
wing("winged:wing_elytra_light_blue", "winged:core_of_flight", "minecraft:elytra", "minecraft:light_blue_wool", "minecraft:light_blue_wool", "minecraft:light_blue_wool")
wing("winged:wing_elytra_light_blue_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:light_blue_wool", "minecraft:light_blue_wool", "minecraft:light_blue_wool")
wing("winged:wing_elytra_light_gray", "winged:core_of_flight", "minecraft:elytra", "minecraft:light_gray_wool", "minecraft:light_gray_wool", "minecraft:light_gray_wool")
wing("winged:wing_elytra_light_gray_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:light_gray_wool", "minecraft:light_gray_wool", "minecraft:light_gray_wool")
wing("winged:wing_elytra_lime", "winged:core_of_flight", "minecraft:elytra", "minecraft:lime_wool", "minecraft:lime_wool", "minecraft:lime_wool")
wing("winged:wing_elytra_lime_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:lime_wool", "minecraft:lime_wool", "minecraft:lime_wool")
wing("winged:wing_elytra_magenta", "winged:core_of_flight", "minecraft:elytra", "minecraft:magenta_wool", "minecraft:magenta_wool", "minecraft:magenta_wool")
wing("winged:wing_elytra_magenta_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:magenta_wool", "minecraft:magenta_wool", "minecraft:magenta_wool")
wing("winged:wing_elytra_orange", "winged:core_of_flight", "minecraft:elytra", "minecraft:orange_wool", "minecraft:orange_wool", "minecraft:orange_wool")
wing("winged:wing_elytra_orange_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:orange_wool", "minecraft:orange_wool", "minecraft:orange_wool")
wing("winged:wing_elytra_pink", "winged:core_of_flight", "minecraft:elytra", "minecraft:pink_wool", "minecraft:pink_wool", "minecraft:pink_wool")
wing("winged:wing_elytra_pink_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:pink_wool", "minecraft:pink_wool", "minecraft:pink_wool")
wing("winged:wing_elytra_purple", "winged:core_of_flight", "minecraft:elytra", "minecraft:purple_wool", "minecraft:purple_wool", "minecraft:purple_wool")
wing("winged:wing_elytra_purple_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:purple_wool", "minecraft:purple_wool", "minecraft:purple_wool")
wing("winged:wing_elytra_red", "winged:core_of_flight", "minecraft:elytra", "minecraft:red_wool", "minecraft:red_wool", "minecraft:red_wool")
wing("winged:wing_elytra_red_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:red_wool", "minecraft:red_wool", "minecraft:red_wool")
wing("winged:wing_elytra_white", "winged:core_of_flight", "minecraft:elytra", "minecraft:white_wool", "minecraft:white_wool", "minecraft:white_wool")
wing("winged:wing_elytra_white_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:white_wool", "minecraft:white_wool", "minecraft:white_wool")
wing("winged:wing_elytra_yellow", "winged:core_of_flight", "minecraft:elytra", "minecraft:yellow_wool", "minecraft:yellow_wool", "minecraft:yellow_wool")
wing("winged:wing_elytra_yellow_creative_flight", "winged:heart_of_the_sky", "minecraft:elytra", "minecraft:yellow_wool", "minecraft:yellow_wool", "minecraft:yellow_wool")
wing("winged:wing_fairyonline", "winged:core_of_flight", "minecraft:diamond", "minecraft:diamond", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_fairyonline_creative_flight", "winged:heart_of_the_sky", "minecraft:diamond", "minecraft:diamond", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_fire_dragon", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:blaze_powder", "winged:dragon_scale", "winged:dragon_scale")
wing("winged:wing_fire_dragon_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:blaze_powder", "winged:dragon_scale", "winged:dragon_scale")
wing("winged:wing_fried_chicken", "winged:core_of_flight", "minecraft:iron_ingot", "winged:fried_chicken", "winged:fried_chicken", "winged:fried_chicken")
wing("winged:wing_fried_chicken_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "winged:fried_chicken", "winged:fried_chicken", "winged:fried_chicken")
wing("winged:wing_glass", "winged:core_of_flight", "winged:irreality_crystal", "minecraft:glass_pane", "minecraft:glass_pane", "minecraft:glass_pane")
wing("winged:wing_glass_creative_flight", "winged:heart_of_the_sky", "winged:irreality_crystal", "minecraft:glass_pane", "minecraft:glass_pane", "minecraft:glass_pane")
wing("winged:wing_glider", "winged:wing_elytra_white", "minecraft:iron_nugget", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_nugget")
wing("winged:wing_glider_creative_flight", "winged:wing_elytra_white_creative_flight", "minecraft:iron_nugget", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_nugget")
wing("winged:wing_golden_beetle", "winged:core_of_flight", "minecraft:spider_eye", "minecraft:gold_ingot", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_golden_beetle_creative_flight", "winged:heart_of_the_sky", "minecraft:spider_eye", "minecraft:gold_ingot", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_green_beetle", "winged:core_of_flight", "minecraft:spider_eye", "minecraft:green_dye", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_green_beetle_creative_flight", "winged:heart_of_the_sky", "minecraft:spider_eye", "minecraft:green_dye", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_green_dragon", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:green_dye", "winged:dragon_scale", "winged:dragon_scale")
wing("winged:wing_green_dragon_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:green_dye", "winged:dragon_scale", "winged:dragon_scale")
wing("winged:wing_greenwing_macaw", "winged:core_of_flight", "minecraft:iron_ingot", "winged:bowl_of_dyes", "minecraft:feather", "minecraft:feather")
wing("winged:wing_greenwing_macaw_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "winged:bowl_of_dyes", "minecraft:feather", "minecraft:feather")
wing("winged:wing_irreality", "winged:core_of_flight", "winged:irreality_crystal", "winged:irreality_crystal", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_irreality_creative_flight", "winged:heart_of_the_sky", "winged:irreality_crystal", "winged:irreality_crystal", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_julianclark_cape", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:carved_pumpkin", "minecraft:snow_block", "minecraft:feather")
wing("winged:wing_julianclark_cape_alt", "winged:core_of_flight", "minecraft:feather", "minecraft:carved_pumpkin", "minecraft:iron_ingot", "minecraft:snow_block")
wing("winged:wing_julianclark_cape_alt_creative_flight", "winged:heart_of_the_sky", "minecraft:feather", "minecraft:carved_pumpkin", "minecraft:iron_ingot", "minecraft:snow_block")
wing("winged:wing_julianclark_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:carved_pumpkin", "minecraft:snow_block", "minecraft:feather")
wing("winged:wing_mapmaker_cape", "winged:core_of_flight", "undefined", "minecraft:yellow_wool", "minecraft:light_blue_wool", "minecraft:light_blue_wool")
wing("winged:wing_mapmaker_cape_creative_flight", "winged:heart_of_the_sky", "undefined", "minecraft:yellow_wool", "minecraft:light_blue_wool", "minecraft:light_blue_wool")
wing("winged:wing_mech_dragon", "winged:core_of_flight", "minecraft:piston", "minecraft:redstone", "winged:dragon_scale", "minecraft:iron_ingot")
wing("winged:wing_mech_dragon_creative_flight", "winged:heart_of_the_sky", "minecraft:piston", "minecraft:redstone", "winged:dragon_scale", "minecraft:iron_ingot")
wing("winged:wing_millionth_cape", "winged:core_of_flight", "winged:irreality_crystal", "undefined", "minecraft:purple_wool", "minecraft:nether_star")
wing("winged:wing_millionth_cape_creative_flight", "winged:heart_of_the_sky", "winged:irreality_crystal", "undefined", "minecraft:purple_wool", "minecraft:nether_star")
wing("winged:wing_minecon_2011_cape", "winged:core_of_flight", "winged:attendee_ticket", "minecraft:red_wool", "minecraft:red_wool", "minecraft:red_wool")
wing("winged:wing_minecon_2011_cape_creative_flight", "winged:heart_of_the_sky", "winged:attendee_ticket", "minecraft:red_wool", "minecraft:red_wool", "minecraft:red_wool")
wing("winged:wing_minecon_2012_cape", "winged:core_of_flight", "winged:attendee_ticket", "minecraft:blue_wool", "minecraft:blue_wool", "minecraft:blue_wool")
wing("winged:wing_minecon_2012_cape_creative_flight", "winged:heart_of_the_sky", "winged:attendee_ticket", "minecraft:blue_wool", "minecraft:blue_wool", "minecraft:blue_wool")
wing("winged:wing_minecon_2013_cape", "winged:core_of_flight", "winged:attendee_ticket", "minecraft:lime_wool", "minecraft:lime_wool", "minecraft:lime_wool")
wing("winged:wing_minecon_2013_cape_creative_flight", "winged:heart_of_the_sky", "winged:attendee_ticket", "minecraft:lime_wool", "minecraft:lime_wool", "minecraft:lime_wool")
wing("winged:wing_minecon_2015_cape", "winged:core_of_flight", "winged:attendee_ticket", "minecraft:cyan_wool", "minecraft:cyan_wool", "minecraft:cyan_wool")
wing("winged:wing_minecon_2015_cape_creative_flight", "winged:heart_of_the_sky", "winged:attendee_ticket", "minecraft:cyan_wool", "minecraft:cyan_wool", "minecraft:cyan_wool")
wing("winged:wing_minecon_2016_cape", "winged:core_of_flight", "winged:attendee_ticket", "minecraft:black_wool", "minecraft:black_wool", "minecraft:black_wool")
wing("winged:wing_minecon_2016_cape_creative_flight", "winged:heart_of_the_sky", "winged:attendee_ticket", "minecraft:black_wool", "minecraft:black_wool", "minecraft:black_wool")
wing("winged:wing_minecon_2019_cape", "winged:core_of_flight", "winged:attendee_ticket", "minecraft:orange_wool", "minecraft:orange_wool", "minecraft:orange_wool")
wing("winged:wing_minecon_2019_cape_creative_flight", "winged:heart_of_the_sky", "winged:attendee_ticket", "minecraft:orange_wool", "minecraft:orange_wool", "minecraft:orange_wool")
wing("winged:wing_mojang_cape", "winged:core_of_flight", "undefined", "minecraft:red_wool", "minecraft:red_wool", "minecraft:red_wool")
wing("winged:wing_mojang_cape_alt", "winged:core_of_flight", "undefined", "minecraft:brown_wool", "minecraft:brown_wool", "minecraft:brown_wool")
wing("winged:wing_mojang_cape_alt_creative_flight", "winged:heart_of_the_sky", "undefined", "minecraft:brown_wool", "minecraft:brown_wool", "minecraft:brown_wool")
wing("winged:wing_mojang_cape_creative_flight", "winged:heart_of_the_sky", "undefined", "minecraft:red_wool", "minecraft:red_wool", "minecraft:red_wool")
wing("winged:wing_mojira_mod_cape", "winged:core_of_flight", "undefined", "minecraft:black_wool", "minecraft:brown_wool", "minecraft:fire_charge")
wing("winged:wing_mojira_mod_cape_creative_flight", "winged:heart_of_the_sky", "undefined", "minecraft:black_wool", "minecraft:brown_wool", "minecraft:fire_charge")
wing("winged:wing_mrmessiah_cape", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:lime_wool", "minecraft:black_wool", "minecraft:magenta_wool")
wing("winged:wing_mrmessiah_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:lime_wool", "minecraft:black_wool", "minecraft:magenta_wool")
wing("winged:wing_phantom", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:lapis_lazuli", "minecraft:phantom_membrane", "minecraft:phantom_membrane")
wing("winged:wing_phantom_alt", "winged:core_of_flight", "minecraft:lapis_lazuli", "minecraft:iron_ingot", "minecraft:phantom_membrane", "minecraft:phantom_membrane")
wing("winged:wing_phantom_alt_creative_flight", "winged:heart_of_the_sky", "minecraft:lapis_lazuli", "minecraft:iron_ingot", "minecraft:phantom_membrane", "minecraft:phantom_membrane")
wing("winged:wing_phantom_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:lapis_lazuli", "minecraft:phantom_membrane", "minecraft:phantom_membrane")
wing("winged:wing_phantom_membrane", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:phantom_membrane", "minecraft:phantom_membrane", "minecraft:phantom_membrane")
wing("winged:wing_phantom_membrane_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:phantom_membrane", "minecraft:phantom_membrane", "minecraft:phantom_membrane")
wing("winged:wing_phoenix", "winged:core_of_flight", "minecraft:gold_ingot", "winged:phoenix_feather", "winged:phoenix_feather", "winged:phoenix_feather")
wing("winged:wing_phoenix_creative_flight", "winged:heart_of_the_sky", "minecraft:gold_ingot", "winged:phoenix_feather", "winged:phoenix_feather", "winged:phoenix_feather")
wing("winged:wing_prismarine_cape", "winged:core_of_flight", "minecraft:prismarine_crystals", "minecraft:prismarine_shard", "minecraft:prismarine_shard", "minecraft:prismarine_shard")
wing("winged:wing_prismarine_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:prismarine_crystals", "minecraft:prismarine_shard", "minecraft:prismarine_shard", "minecraft:prismarine_shard")
wing("winged:wing_purple_beetle", "winged:core_of_flight", "minecraft:spider_eye", "minecraft:purple_dye", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_purple_beetle_creative_flight", "winged:heart_of_the_sky", "minecraft:spider_eye", "minecraft:purple_dye", "winged:irreality_crystal", "winged:irreality_crystal")
wing("winged:wing_rainbow", "winged:core_of_flight", "minecraft:iron_ingot", "winged:bowl_of_dyes", "undefined", "undefined")
wing("winged:wing_rainbow_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "winged:bowl_of_dyes", "undefined", "undefined")
wing("winged:wing_red_dragon", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:red_dye", "winged:dragon_scale", "winged:dragon_scale")
wing("winged:wing_red_dragon_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:red_dye", "winged:dragon_scale", "winged:dragon_scale")
wing("winged:wing_redstone", "winged:core_of_flight", "minecraft:piston", "minecraft:redstone_block", "minecraft:redstone_block", "minecraft:redstone_block")
wing("winged:wing_redstone_creative_flight", "winged:heart_of_the_sky", "minecraft:piston", "minecraft:redstone_block", "minecraft:redstone_block", "minecraft:redstone_block")
wing("winged:wing_scrolls_cape", "winged:core_of_flight", "undefined", "minecraft:yellow_wool", "minecraft:iron_ingot", "minecraft:yellow_wool")
wing("winged:wing_scrolls_cape_creative_flight", "winged:heart_of_the_sky", "undefined", "minecraft:yellow_wool", "minecraft:iron_ingot", "minecraft:yellow_wool")
wing("winged:wing_shulker", "winged:core_of_flight", "minecraft:diamond", "minecraft:shulker_shell", "minecraft:popped_chorus_fruit", "minecraft:popped_chorus_fruit")
wing("winged:wing_shulker_creative_flight", "winged:heart_of_the_sky", "minecraft:diamond", "minecraft:shulker_shell", "minecraft:popped_chorus_fruit", "minecraft:popped_chorus_fruit")
wing("winged:wing_spooky", "winged:wing_elytra_black", "minecraft:jack_o_lantern", "minecraft:torch", "minecraft:glowstone_dust", "minecraft:glowstone_dust")
wing("winged:wing_spooky_alt", "winged:wing_elytra_black", "minecraft:jack_o_lantern", "minecraft:soul_torch", "minecraft:glowstone_dust", "minecraft:glowstone_dust")
wing("winged:wing_spooky_alt_creative_flight", "winged:wing_elytra_black_creative_flight", "minecraft:jack_o_lantern", "minecraft:soul_torch", "minecraft:glowstone_dust", "minecraft:glowstone_dust")
wing("winged:wing_spooky_creative_flight", "winged:wing_elytra_black_creative_flight", "minecraft:jack_o_lantern", "minecraft:torch", "minecraft:glowstone_dust", "minecraft:glowstone_dust")
wing("winged:wing_tiny_bird", "winged:core_of_flight", "minecraft:iron_ingot", null, "minecraft:feather", null)
wing("winged:wing_tiny_bird_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", null, "minecraft:feather", null)
wing("winged:wing_tnt", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:gunpowder", "minecraft:tnt", "minecraft:paper")
wing("winged:wing_tnt_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:gunpowder", "minecraft:tnt", "minecraft:paper")
wing("winged:wing_turtle_cape", "winged:core_of_flight", "minecraft:iron_ingot", "minecraft:scute", "minecraft:scute", "minecraft:scute")
wing("winged:wing_turtle_cape_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "minecraft:scute", "minecraft:scute", "minecraft:scute")
wing("winged:wing_usa", "winged:wing_eagle", "minecraft:white_dye", "minecraft:lapis_lazuli", "minecraft:red_dye", "minecraft:white_dye")
wing("winged:wing_usa_creative_flight", "winged:wing_eagle_creative_flight", "minecraft:white_dye", "minecraft:lapis_lazuli", "minecraft:red_dye", "minecraft:white_dye")
wing("winged:wing_usa", "winged:wing_eagle", "minecraft:red_dye", "minecraft:lapis_lazuli", "minecraft:white_dye", "minecraft:red_dye")
wing("winged:wing_usa_creative_flight", "winged:wing_eagle_creative_flight", "minecraft:red_dye", "minecraft:lapis_lazuli", "minecraft:white_dye", "minecraft:red_dye")
wing("winged:wing_vex", "winged:core_of_flight", "minecraft:iron_ingot", "winged:vex_essence", "winged:vex_essence", "winged:vex_essence")
wing("winged:wing_vex_creative_flight", "winged:heart_of_the_sky", "minecraft:iron_ingot", "winged:vex_essence", "winged:vex_essence", "winged:vex_essence")
wing("winged:wing_xmas_star", "winged:wing_elytra_red", "minecraft:iron_ingot", "minecraft:white_dye", "minecraft:white_dye", "minecraft:gold_nugget")
wing("winged:wing_xmas_star_creative_flight", "winged:wing_elytra_red_creative_flight", "minecraft:iron_ingot", "minecraft:white_dye", "minecraft:white_dye", "minecraft:gold_nugget")
wing("winged:wing_xmas_tree", "winged:wing_elytra_red", "minecraft:glowstone_dust", "minecraft:gold_nugget", "winged:bowl_of_dyes", "minecraft:spruce_sapling")
wing("winged:wing_xmas_tree_creative_flight", "winged:wing_elytra_red_creative_flight", "minecraft:glowstone_dust", "minecraft:gold_nugget", "winged:bowl_of_dyes", "minecraft:spruce_sapling")
}
